name: CD

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Extrai metadados da imagem
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USER }}/calculadora-mobile
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build e push da imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
